import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./global.css";


const RobotoFont = Roboto({subsets:['latin'],display:'swap'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${RobotoFont.className}`}>
      <body>{children}</body>
    </html>
  );
}
